### ISSUE TITLE
Milestone 2 checklist

### ISSUE THREAD

**Issue by jianructose** [UBC-MDS/majacloud#17]
[Milestone 2: The purpose of this milestone is to move our data to the cloud and get comfortable working there.](https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/Milestone2.ipynb)

Milestone 2 checklist
- [x] Setup your EC2 instance with JupyterHub.
- [x] Install all necessary things needed in your UNIX server (amazon ec2 instance).
- [x] Setup your S3 bucket.
- [x] Move the data that you wrangled in your last milestone to s3.
- [x] Get the data from S3 in your notebook and make data ready for machine learning.

**Comment by shoebillm** [comment]
- [X] Setup your EC2 instance with JupyterHub.
<img width="1150" alt="Screen Shot 2021-04-12 at 1 31 58 PM" src="https://user-images.githubusercontent.com/48242437/114459322-382f7a00-9b95-11eb-93d6-ed277d5724ee.png">

**Comment by shoebillm** [comment]
- [X] Install all necessary things needed in your UNIX server (amazon ec2 instance)
<img width="578" alt="Screen Shot 2021-04-12 at 3 11 58 PM" src="https://user-images.githubusercontent.com/48242437/114588793-e8f05480-9c3b-11eb-920c-0c51fa10850b.png">

**Comment by shoebillm** [comment]
- [X] Setup your S3 bucket.
- [X] Move the data that you wrangled in your last milestone to s3.
![image](https://user-images.githubusercontent.com/48242437/114588398-80a17300-9c3b-11eb-913a-5f1b3d8a4ab5.png)

**Comment by shoebillm** [comment]
- [X] Setup your EC2 instance with JupyterHub.
<img width="593" alt="Screen Shot 2021-04-13 at 3 26 41 PM" src="https://user-images.githubusercontent.com/48242437/114629283-2b7e5500-9c6d-11eb-8f94-b3682364c4bd.png">
