### ISSUE TITLE
Milestone 3 checklist

### ISSUE THREAD

**Issue by jianructose** [UBC-MDS/majacloud#28]
# [Milestone 3 checklist](https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/Milestone3.ipynb) :
- [x] Setup your EMR cluster with Spark & JupyterHub.
- [x] Setup your WebBrowser(Firefox) for EMR.
- [x] Develop a ML model using scikit-learn. (We will be using this model to deploy for our next milestone.)
    - [x] train on ensemble model
    - [x] prepare for deploying model for m4
- [x] Obtain best hyperparameter settings using spark's MLlib.

**Comment by shoebillm** [comment]
- [X] Setup your EMR cluster with Spark & JupyterHub.

<img width="764" alt="Screen Shot 2021-04-19 at 1 13 38 PM" src="https://user-images.githubusercontent.com/48242437/115297741-68d15f80-a111-11eb-8a99-8df426448070.png">

**Comment by shoebillm** [comment]
- [X] Setup your WebBrowser(Firefox) for EMR.
<img width="569" alt="Screen Shot 2021-04-19 at 2 20 38 PM" src="https://user-images.githubusercontent.com/48242437/115304947-6d4e4600-a11a-11eb-8039-f2383188a987.png">


<img width="997" alt="Screen Shot 2021-04-19 at 2 47 55 PM" src="https://user-images.githubusercontent.com/48242437/115307610-514ca380-a11e-11eb-95c0-c3ba3ea21112.png">
